#Case I
setwd("C:/Users/annet/OneDrive/Desktop/HKUST/Academic/Business Analytics/Sem2/Business Analytics in R/Data")
amazon <- read.table("amazon_hosts.csv", header=T, sep=",")
attach(amazon)
names(amazon)
str(amazon)
summary(amazon)
tail(amazon)
amazon_new <- data.frame(amazon[1:11,], row.names = seq(1,11,by=1))
levels(amazon_new$Host) = c(levels(amazon_new$Host),'other hosts')
amazon_new$Host
str(amazon_new)
amazon_new[12,]=list('other hosts', sum(tail(amazon$Count,11)),0)
amazon_new$Proportion = amazon_new$Count/sum(amazon_new$Count)
amazon_new
str(amazon_new)
sorted = amazon_new[order(amazon_new$Count),]
sorted
barplot(sorted$Count, names.arg = sorted$Host, horiz = TRUE, las = 2, main = "All visits to Amazon")
barplot(sorted$Count[1:10], names.arg = sorted$Host[1:10], horiz = TRUE, las=2, main='Bar Chart of Top 10 Hosts')
par(mar=c(0,0,5,0))
pie(sorted$Count[1:10], sorted$Host[1:10], main='Pie Chart of Top 10 hosts')
library(gmodels)
rm(list=ls())
host_purchase = read.csv("three_hosts.csv", sep = ',')
names(host_purchase)
str(host_purchase)
host_purchase$purchase = relevel(host_purchase$purchase, "Yes")
host_purchase
summary(host_purchase)
host_table = CrossTable(host_purchase$purchase, host_purchase$host, prop.chisq = F, prop.c = F, prop.t = F)
host_table <- CrossTable(host_purchase$host, host_purchase$purchase, prop.chisq = F, prop.c = F, prop.t = F)
mosaicplot(host_table$t, color = c("grey","lightgreen"), xlab = "Host", ylab = "Purchase", main = "Mosaic Plot")
chisq.test(host_purchase$host, host_purchase$purchase)
msnrecipe <- subset(host_purchase, host %in%
                c("msn.com", "recipesource.com"))
chisq.test(msnrecipe$host, msnrecipe$purchase)           
msnyahoo <- subset(host_purchase, host %in%
                     c("msn.com", "yahoo.com"))
chisq.test(msnyahoo$host, msnyahoo$purchase)
host_msn <- subset(host_purchase, host == "msn.com")
host_recipesource <- subset(host_purchase, host=="recipesource.com")
host_yahoo <- subset(host_purchase, host =="yahoo.com")
t.test(as.numeric(host_msn$purchase=="Yes"))
t.test(as.numeric(host_recipesource$purchase=="Yes"))
t.test(as.numeric(host_yahoo$purchase=="Yes"))
msnrecipe.purchase <- as.numeric(msnrecipe$purchase=="Yes")
t.test(msnrecipe.purchase ~ msnrecipe$host)
msnyahoo.purchase <- as.numeric(msnyahoo$purchase=="Yes")
t.test(msnyahoo.purchase ~ msnyahoo$host)
