setwd("C:/Users/annet/OneDrive/Desktop/HKUST/Academic/Business Analytics/Sem2/Business Analytics in R/Data ")
facebook <- read.csv("facebook.csv", header=TRUE)
names(facebook)
str(facebook)
attach(facebook)
unique(Type)
unique(Post_time)
summary(facebook)
category <- as.factor(Category)
type <- as.factor(Type)        
post_month <- (as.factor(Post_month))
post_day <- as.factor(Post_day)
paid <- as.factor(Paid)
boxplot(Nbr.Post_Clicks ~ category, main = "Number of Post Click",
        xlab = "category", ylab = "Number of clicks")
boxplot(Nbr.Post_Clicks ~ paid, main = "Number of Post Clicks", xlab = "Paid", ylab = "Number of clicks")
boxplot(Nbr.Post_Clicks ~ type, main = "Number of Post Clicks", xlab = "Type", ylab ="Number of Clicks") 
library(gmodels)
par(mar=c(4,4,4,4))
host_table <- CrossTable(paid, type, prop.chisq = FALSE, prop.c = TRUE, prop.r = TRUE, prop.t = TRUE)
mosaicplot(host_table$t, color=c("light blue", "light green"), xlab = "Paid", ylab = "Type", main = "Mosaic Plot")
mean(Nbr.Post_Clicks[paid==1])
mean(Nbr.Post_Clicks[paid == 0])
t.test(Nbr.Post_Clicks~Paid)
